custom <- c(
  "grey65",
  "darkgoldenrod1",
  "cornflowerblue",
  "forestgreen",
  "tomato2",
  "mediumpurple1",
  "turquoise3",
  "lightgreen",
  "navy",
  "plum1",
  "red4",
  "khaki1",
  "tan4",
  "cadetblue1",
  "olivedrab3",
  "darkorange2",
  "burlywood2",
  "violetred3",
  "aquamarine3",
  "grey30",
  "lavender",
  "blueviolet",
  "grey10",
  "pink3",
  "turquoise4",
  "darkkhaki",
  "magenta",
  "blue",
  "green",
  "red",
  "darkolivegreen",
  "orchid1",
  "springgreen",
  "dodgerblue4",
  "deepskyblue",
  "palevioletred4",
  "gold4",
  "maroon1",
  "lightyellow",
  "greenyellow",
  "purple4",
  "yellow")

custom_light <- c(
  "grey65",
  "darkgoldenrod1",
  "cornflowerblue",
  "forestgreen",
  "tomato2",
  "mediumpurple1",
  "turquoise3",
  "lightgreen",
  "plum1",
  "red4",
  "khaki1",
  "tan4",
  "blue",
  "cadetblue1",
  "olivedrab3",
  "darkorange2",
  "burlywood2",
  "violetred3",
  "aquamarine3",
  "lavender",
  "blueviolet",
  "pink3",
  "turquoise4",
  "darkkhaki",
  "magenta",
  "green",
  "red",
  "darkolivegreen",
  "orchid1",
  "springgreen",
  "dodgerblue4",
  "deepskyblue",
  "palevioletred4",
  "gold4",
  "maroon1",
  "lightyellow",
  "greenyellow",
  "yellow")

# bg_col: '#273238'
# "#34312F"
material <- c(
  "#CC6666",
  "#DF935F",
  "#81A3BE",
  "#B5BD68",
  "#707880",
  "#B394BB",
  "#4F5C69",
  "#CC0000",
  "#F1CC37",
  "#5787DA",
  "#25B876",
  "#5E3582",
  "#93C5DE",
  "#B7A7C5",
  "#2E90B0",
  "#C5C8C6",
  "#50C186")

usethis::use_data(custom, custom_light, material,
                  overwrite = T, internal = T)
